### ISSUE TITLE
Progress is spelled incorrectly

### ISSUE THREAD

**Issue by sbschase** [progress/Spark-Toolkit#14]
In the first line on page 2, Progress is spelled incorrectly:
The **Progres** Spark Toolkit is a reference implementation of the Common 

docs/Spark Components Guide.docx

**Comment by DustinGrau-PSC** [comment]
Good catch! This has been corrected, and I've checked the remaining documents for any similar mis-spellings. The documents have also been updated to reflect the required minimum version of OpenEdge, and the month of publication/update for the latest release.
