### ISSUE TITLE
Required managers

### ISSUE THREAD

**Issue by bstanford-dmsi** [progress/Spark-Toolkit#22]
In the StartupManager.cls there are only 2 managers which are required.  However, all managers whether configured in startup.json or not are defaulted to required.  I don't find a mechanism to set a manager as not required, without changing the method checkAllManagersAreListed().  If I am missing something please let me know.

**Comment by DustinGrau-PSC** [comment]
CCS dictates that there are 3 critical managers that must be present with any Application instance: Startup, Session, and Service. For the Spark-Toolkit, which I remind you is a reference implementation, attempts to check for the following as available managers: Connection, Logging, State, and Translation. Later versions made the Catalog manager optional, and further made the Schema manager required only in conjunction with the Catalog manager.
What is the manager that you are attempting to make non-required?

**Comment by bstanford-dmsi** [comment]
At the moment, I'm thinking the translationmanager and possibly the connectionmanager.   If there is something in the reference implementation that requires them, then no problem.  I was just thinking the SSS managers were the only required.

**Comment by DustinGrau-PSC** [comment]
Yes, if you were building your own application by the CCS standards, then you would only be required to start the 3 (Triple-S) managers. But since you are utilizing the provided reference implementation offered by the Spark-Toolkit, then certain managers are required as they are utilized within other classes. The TranslationManager has references in various other supporting libraries and so it must be checked and registered as a required manager. The ConnectionManager does not appear to have any such dependencies so I can work to make that non-required by default. Does this make sense?

**Comment by bstanford-dmsi** [comment]
Sure, makes perfect sense.  Thanks.

**Comment by DustinGrau-PSC** [comment]
Were these the only managers that were of concern? If the ConnectionManager can be safely removed, but the TranslationManager remain, does that help at all? As you found, even if you did not specify these managers in the startup.json the code you noted ensures the required managers are internally registered and so long as the Spark.pl is present the manager will be loaded without error. Is the end goal to reduce the number of started object instances?

**Comment by bstanford-dmsi** [comment]
I’m just concerned about bloating the session, If  we don’t need it or use it, then it don’t load it up.  Yes, I believe we make use of the others.

**Comment by DustinGrau-PSC** [comment]
Understood. I'll work to remove the ConnectionManager which is not used in any of the demo applications, though I cannot disable the TranslationManager without some significant code changes. If you are following the annotated business entity pattern then it would be possible to remove the Catalog and Schema managers from your startup.json, though if you depend on the dynamic discovery of your API's then you would need these to remain listed. This is demonstrated between the Sports and DynSports, respectively.

**Comment by bstanford-dmsi** [comment]
Another issue I’m running into is not being able to extend ClientContext.cls with additional property members.

The use case:
All of our business logic requires a “BranchID”.  It is being passed in via a request header and I would like to store it in a ClientContext:pcBranch member property instead of a user property from the ttUserSessionProp.  Storing it in a member property makes it is easily accessible and more performant; there is really no reason to have it saved to the datastore as it could be a different value with each request.

ClientContext:initializeContext():
    THIS-OBJECT:pcBranch = oWebRequest:GetHeader("BranchID"):value
versus
   this-object:SetUserProperty(“BranchID”, oWebRequest:GetHeader("BranchID"):value)

FooBE.cls
   If oCurrentContext:pcBranch = “123” then .
versus
   if  oCurrentContext:getUserProperty (“BranchID”) = “123” then .

There are probably other ways to do this, but this was my initial thought.

**Comment by DustinGrau-PSC** [comment]
I will work with you on the latter (new) question as that's more specific to your use of the toolkit. Thank you for the manager question, and as noted I will see what can be done to reduce any unnecessary managers.
